import type { NextPage } from 'next'
import Head from 'next/head'
import { SyntheticEvent, useEffect, useState } from 'react'
import BreakingBadCards from '../components/cards/breakingBadCards'
import Navbar from '../components/navbar/navbar'
import styles from '../components/search/search.module.css'

const BreakingBad: NextPage = () => {
  const [data, setData] = useState([])
  const [searchInput, setSearchInput] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [loading, setLoading] = useState(true)
  let API_ENDPOINT = `https://www.breakingbadapi.com/api/characters`
  if (searchQuery.length > 0) {
    API_ENDPOINT = `https://www.breakingbadapi.com/api/characters?name=${searchQuery}`
  }

  useEffect(() => {
    ;(async () => {
      const response = await fetch(API_ENDPOINT)
      const data = await response.json()
      setData(data)
      setLoading(false)
    })()
  }, [API_ENDPOINT])

  const handleSearch = (e: SyntheticEvent) => {
    e.preventDefault()
    setSearchQuery(searchInput)
  }

  return (
    <div>
      <Head>
        <title>Breaking Bad Universe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='App'>
        <Navbar />
        <h3 className='text-center my-4 ubuntu'>
          Search Breaking Bad Character
        </h3>
        <form
          className='d-flex flex-sm-row flex-column align-items-center justify-content-center gap-4 mb-5'
          onSubmit={handleSearch}
        >
          <input
            type='search'
            className={styles.input}
            placeholder='Search for characters'
            onChange={(e) => {
              setSearchInput(e.target.value)
            }}
          />
          <button className={`${styles.btn} btn btn-primary fs-5`}>
            Search
          </button>
        </form>
        <div className='container'>
          <div className='row d-flex justify-content-center flex-wrap'>
            <div className='col-lg-8 col-12'>
              <div className='row d-flex justify-content-center'>
                {loading ? (
                  <div style={{ display: 'grid', placeItems: 'center' }}>
                    <div className='spinner-border text-primary' role='status'>
                      <span className='visually-hidden'>Loading...</span>
                    </div>
                  </div>
                ) : (
                  <BreakingBadCards results={data} />
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default BreakingBad
