import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Cards from '../components/cards/cards'
import Filter from '../components/filter/filter'
import Navbar from '../components/navbar/navbar'
import Pagination from '../components/pagination/pagination'
import Search from '../components/search/search'
import { DataProps } from '../types'

const Home: NextPage = () => {
  const [pageNum, setPageNum] = useState<number>(1)
  const [searchQuery, setSearchQuery] = useState<string>('')
  const [status, setStatus] = useState<string>('')
  const [gender, setGender] = useState<string>('')
  const [species, setSpecies] = useState<string>('')
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const { info, results } = data as unknown as DataProps
  const API_ENDPOINT = `https://rickandmortyapi.com/api/character/?page=${pageNum}&name=${searchQuery}&status=${status}&gender=${gender}&species=${species}`

  useEffect(() => {
    ;(async () => {
      const response = await fetch(API_ENDPOINT)
      const data = await response.json()
      setData(data)
      setLoading(false)
    })()
  }, [API_ENDPOINT])

  return (
    <div>
      <Head>
        <title>Rick & Morty Universe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='App'>
        <Navbar />
        <h3 className='text-center my-4 ubuntu'>Characters</h3>
        <Search setPageNum={setPageNum} setSearchQuery={setSearchQuery} />
        <div className='container'>
          <div className='row d-flex justify-content-center flex-wrap'>
            <Filter
              setState={{ setStatus, setGender, setSpecies }}
              setPageNum={setPageNum}
            />
            <div className='col-lg-8 col-12'>
              <div className='row d-flex justify-content-center'>
                {loading ? (
                  <div style={{ display: 'grid', placeItems: 'center' }}>
                    <div className='spinner-border text-primary' role='status'>
                      <span className='visually-hidden'>Loading...</span>
                    </div>
                  </div>
                ) : (
                  <Cards results={results} />
                )}
              </div>
            </div>
          </div>
        </div>
        <Pagination info={info} pageNum={pageNum} setPageNum={setPageNum} />
      </div>
    </div>
  )
}

export default Home
